version: "2.1"

services:

  settings-tp:
    image: hyperledger/sawtooth-tp_settings:0.8
    container_name: sawtooth-settings-tp-default
    expose:
      - 4004
    depends_on:
      - validator
    entrypoint: settings-tp -vv tcp://validator:4004

  intkey-tp-python:
    image: hyperledger/sawtooth-tp_intkey_python:0.8
    container_name: sawtooth-intkey-tp-python-default
    expose:
      - 4004
    depends_on:
      - validator
    entrypoint: intkey-tp-python -vv tcp://validator:4004

  xo-tp-python:
    image: hyperledger/sawtooth-tp_xo_python:0.8
    container_name: sawtooth-xo-tp-python-default
    expose:
      - 4004
    depends_on:
      - validator
    entrypoint: xo-tp-python -vv tcp://validator:4004

  validator:
    image: hyperledger/sawtooth-validator:0.8
    container_name: sawtooth-validator-default
    expose:
      - 4004
    ports:
      - "4004:4004"
    # start the validator with an empty genesis batch
    entrypoint: "bash -c \"\
        sawtooth admin keygen && \
        sawtooth keygen my_key && \
        sawtooth config genesis -k /root/.sawtooth/keys/my_key.priv && \
        sawtooth admin genesis config-genesis.batch && \
        sawtooth-validator -vv \
          --endpoint tcp://validator:8800 \
          --bind component:tcp://eth0:4004 \
          --bind network:tcp://eth0:8800 \
        \""

  rest-api:
    image: hyperledger/sawtooth-rest_api:0.8
    container_name: sawtooth-rest-api-default
    expose:
      - 4004
      - 8080
    ports:
      - "8080:8080"
    depends_on:
      - validator
    entrypoint: sawtooth-rest-api --connect tcp://validator:4004 --bind rest-api:8080

  client:
    image: hyperledger/sawtooth-all:0.8
    container_name: sawtooth-client-default
    expose:
      - 8080
      - 4004
    depends_on:
      - rest-api
    entrypoint: "bash -c \"\
        sawtooth keygen && \
        tail -f /dev/null \
        \""
